apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stampede-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stampede-io/STAM-gitops.git
    targetRevision: Dev
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
